### ISSUE TITLE
stopping and starting docker-compose api service empties the database

### ISSUE THREAD

**Issue by m59peacemaker** [mirumee/saleor-platform#64]
To reproduce:
follow the instructions - [how to run it](https://github.com/mirumee/saleor-platform#how-to-run-it)
```sh
docker-compose stop api
docker-compose up api
```
If the database is not empty/broken now, run the above (stop api && up api) again. For me, this consistently causes the database to become empty.

**Comment by balibebas** [comment]
@m59peacemaker did I just hit your issue? I see you already have a pull up. haven't tried it yet but this looks like like it's probably the root cause of what I'm seeing in https://github.com/mirumee/saleor-platform/issues/69

**Comment by m59peacemaker** [comment]
Yep. Sounds like the same issue. That simple change in the PR should fix it.

**Comment by balibebas** [comment]
Curious as to why this issue exists in the first place I wonder if [the compose downgrade](https://github.com/mirumee/saleor-platform/commit/09b73adc89766179ebc9da9119c2249249c3eb8c#diff-4e5e90c6228fd48698d074241c2ba760L1) 7 months ago could be the root cause of the issue. Strange I've never seen anyone downgrade a compose file before...
